openapi: 3.0.3
info:
  title: EasyTrip API
  description: |-
    API documentation for the Trip Planner web application
  version: 1.0.0
servers:
  - url: https://easytrip-api-production.up.railway.app/api/v1

tags:
  - name: Trip
  - name: User
  - name: Auth
    
paths:
  /trips:
    x-swagger-router-controller: ''
    post:
      tags:
        - Trip
      summary: Add a new trip
      operationId: addTrip
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 400
                message: Invalid Trip
        '401':
          description: Unauthenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 401
                message: You must be authenticated to access this data
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
        - user_auth: []
    get:
      tags:
        - Trip
      summary: Get all trips
      operationId: getAllTrips
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key

        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
                
  /trips/{tripId}:
    get:
      tags:
        - Trip
      summary: Find a trip by ID
      operationId: getTrip
      parameters:
        - name: tripId
          in: path
          description: Id of the trip
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '404':
          description: Trip not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 404
                message: Trip Not Found
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
    put:
      tags:
        - Trip
      summary: Update an existing trip
      operationId: updateTrip
      parameters:
        - name: tripId
          in: path
          description: Id of the trip
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'   
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 400
                message: Invalid Trip
        '401':
          description: Unauthenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 401
                message: You must be authenticated to access this data
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '404':
          description: Trip not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 404
                message: Trip Not Found
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
        - user_auth: []
    delete:
      tags:
        - Trip
      summary: Deletes a trip
      operationId: deleteTrip
      parameters:
        - name: tripId
          in: path
          description: Id of the trip
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '401':
          description: Unauthenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 401
                message: You must be authenticated to access this data
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '404':
          description: Trip not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 404
                message: Trip Not Found
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
        - user_auth: []
  
  /trips/budget:
    get:
      tags:
        - Trip
      summary: Find trips by budget
      operationId: getTripsByBudget
      parameters:
        - name: startDate
          in: query
          description: the starting date
          required: true
          schema:
            type: string
        - name: endDate
          in: query
          description: the ending date
          required: true
          schema:
            type: string
        - name: budget
          in: query
          description: the budget
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  allOf:
                    - $ref: '#/components/schemas/Trip'
                    - type: object
                      properties:
                        n_trip_days:
                          type: integer
                        total_price:
                          type: integer
                        exchange_rate:
                          type: number
                        meals:
                          type: array
                          items:
                            type: string
                        weather:
                          type: array
                          items:
                            type: object
                            properties:
                              day:
                                type: number
                              min:
                                type: number
                              max:
                                type: number
                              night:
                                type: number
                              eve:
                                type: number
                              morn:
                                type: number
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 400
                message: Invalid Input
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []

  /trips/country:
    get:
      tags:
        - Trip
      summary: Find trips by country
      operationId: getTripsByCountry
      parameters:
        - name: startDate
          in: query
          description: the starting date
          required: true
          schema:
            type: string
        - name: endDate
          in: query
          description: the ending date
          required: true
          schema:
            type: string
        - name: destCountry
          in: query
          description: destination country
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  allOf:
                    - $ref: '#/components/schemas/Trip'
                    - type: object
                      properties:
                        n_trip_days:
                            type: integer
                        total_price:
                          type: integer
                        exchange_rate:
                          type: number
                        meals:
                          type: array
                          items:
                            type: string
                        weather:
                          type: array
                          items:
                            type: object
                            properties:
                              day:
                                type: number
                              min:
                                type: number
                              max:
                                type: number
                              night:
                                type: number
                              eve:
                                type: number
                              morn:
                                type: number
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 400
                message: Invalid Input
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
                
  /users:
    post:
      tags:
        - User
      summary: Add a new user
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'   
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 400
                message: Invalid Input
        '401':
          description: Unauthenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 401
                message: You must be authenticated to access this data
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '409':
          description: User Already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 409
                message: User Already Exists
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
        - user_auth: []
    get:
      tags:
        - User
      summary: Get All Users
      operationId: getAllUsers
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 401
                message: You must be authenticated to access this data
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
                
  /auth/getkey:
    get:
      tags:
        - Auth
      summary: Get authentification key
      operationId: getkey
      parameters:
        - in: header
          name: client_id
          schema:
            type: string
          required: true 
        - in: header
          name: secret
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  key: 
                    type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 400
                message: Invalid Input
        '401':
          description: Invalid Credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 401
                message: Invalid Credentials
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
  /auth/user:
    get:
      tags:
        - Auth
      summary: Get the current User
      operationId: getCurrentUser
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/User'
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
  /auth/logout:
    get:
      tags:
        - Auth
      summary: Logout
      operationId: logout
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/User'
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
                
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 400
                message: Invalid Input
        '401':
          description: Invalid Credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 401
                message: Invalid Credentials
        '403':
          description: Invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 403
                message: Invalid or Missing API key
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                status: 500
                message: Internal error
      security:
        - api_key: []
components:
  schemas:
    Trip:
      type: object
      properties:
        _id:
          type: string
          readOnly: true
        city:
          type: string
        country:
          type: string
        ticket:
          type: integer
        daily_accommodation:
          type: integer
        daily_food:
          type: integer
        daily_miscellaneous:
          type: integer
        image:
          type: string
        currency:
          type: string
          readOnly: true
    User:
      type: object
      properties:
        _id:
          type: string
          readOnly: true
        username:
          type: string
        password:
          type: string
          writeOnly: true
    Error:
      type: object
      properties:
        success:
          type: boolean
        status:
          type: number
        message:
          type: string
          
  securitySchemes:
    user_auth:
      type: apiKey
      in: cookie
      name: connect.sid
    api_key:
      type: apiKey
      name: key
      in: header
          